### ISSUE TITLE
add model to Hugging Face 

### ISSUE THREAD

**Issue by AK391** [jjeamin/anime_style_transfer_pytorch#1]
Great project, would you be interested in adding this model to Hugging Face and a web demo with Gradio to showcase the project?

**Comment by jjxxmiin** [comment]
Sorry for the late reply. 

The sample image is a cherry pick image. 

Maybe more tuning is needed. 

I will post it later.

**Comment by AK391** [comment]
@jjeamin sounds good, let me know if you need help setting gradio demo similar to https://huggingface.co/spaces/akhaliq/AnimeGANv2 or https://huggingface.co/spaces/akhaliq/ArcaneGAN

**Comment by jjxxmiin** [comment]
Now, you can start gradio demo 

Here -> https://huggingface.co/spaces/jjeamin/ArcaneStyleTransfer

**Comment by AK391** [comment]
@jjeamin Gradio just released v3.0 Blocks along with the Gradio Blocks Event: https://huggingface.co/Gradio-Blocks, it would be great to have an updated blocks version of this demo in the event. Thanks
