### ISSUE TITLE
have option to not align input in demo

### ISSUE THREAD

**Issue by AK391** [jjeamin/anime_style_transfer_pytorch#4]
I have been testing the demo https://huggingface.co/spaces/jjeamin/ArcaneStyleTransfer and I think by adding a option to align faces or not would be good similar to https://huggingface.co/spaces/akhaliq/ArcaneGAN, users might not want to crop the face

**Comment by AK391** [comment]
for example input and output with no face alignment
<img width="1296" alt="Screen Shot 2022-04-28 at 1 23 42 AM" src="https://user-images.githubusercontent.com/81195143/165684036-3e844278-e020-49e1-aa6f-edaef3d17324.png">

**Comment by jjxxmiin** [comment]
My model does not support "no face alignment" because it is difficult to style transfer other parts except the face.

You can also test it out using my model -> https://huggingface.co/jjeamin/ArcaneStyleTransfer/tree/main.

**Comment by AK391** [comment]
@jjeamin ok I think so far the model does ok if the face is not too far off from the expected input (aligned face)
![FRaRMdMXwAAjOy_](https://user-images.githubusercontent.com/81195143/165793875-817d186d-3826-4956-807c-7d84680b02d0.jpeg)

**Comment by jjxxmiin** [comment]
Added face alignment selection button. But the performance is poor.
