### ISSUE TITLE
 I trained so poorly？

### ISSUE THREAD

**Issue by watertianyi** [jjeamin/anime_style_transfer_pytorch#5]
100 pairs of data sets with 1024X1024 resolution are trained according to 512, and the pixel2pixelHD inference is used. Why is the result so poor? Do you know why? The data set pairing adopted is here :https://github.com/Sxela/face2comics
![image](https://user-images.githubusercontent.com/29244715/224199106-ae0992af-140c-486c-84ad-f3f55c482493.png)

**Comment by jjxxmiin** [comment]
In my opinion, the quality of the dataset is very good.

Why did you trained using only 100 pairs?

I think adding more dataset will get good results.

**Comment by watertianyi** [comment]
@jjeamin 
Thank you for your timely reply. I have increased the data to 3000 pairs or 6000 pieces of data for training, but the test data is shown below, which is not very ideal. For example, Bill Gates is not very good, especially the background and clothes. Do you know how to do to achieve those effects on your page, hope to guide.
![image](https://user-images.githubusercontent.com/29244715/224588854-ea222098-e0ee-4e73-9c9e-8d2db3f707dd.png)
![image](https://user-images.githubusercontent.com/29244715/224588903-c9ab9545-4dfa-4f47-a8b1-9b5babe21c07.png)

**Comment by jjxxmiin** [comment]
I think adding data augmentation method(rotation, shift, zoomin, zoomout) to your pix2pixHD code. 

pix2pixhd/data/aligned_dataset.py

```python
import os.path
import cv2
import numpy as np
import albumentations as A
from albumentations.pytorch.transforms import ToTensorV2
from data.base_dataset import BaseDataset, get_params, get_transform
from data.image_folder import make_dataset
from PIL import Image

transform = A.Compose([
    A.ShiftScaleRotate(scale_limit=[-0.5, 0.5], rotate_limit=45, p=0.3, border_mode=cv2.BORDER_CONSTANT, value=(0, 0, 0)),
    A.HorizontalFlip(p=0.5),
    A.Normalize(
        mean = [0.5, 0.5, 0.5], 
        std = [0.5, 0.5, 0.5],
    ),
    ToTensorV2()
],
additional_targets={'style': 'image'})

class AlignedDataset(BaseDataset):
    def initialize(self, opt):
        self.opt = opt
        self.root = opt.dataroot    

        ### input A (label maps)
        dir_A = '_A' if self.opt.label_nc == 0 else '_label'
        self.dir_A = os.path.join(opt.dataroot, opt.phase + dir_A)
        self.A_paths = sorted(make_dataset(self.dir_A))

        ### input B (real images)
        if opt.isTrain or opt.use_encoded_image:
            dir_B = '_B' if self.opt.label_nc == 0 else '_img'
            self.dir_B = os.path.join(opt.dataroot, opt.phase + dir_B)  
            self.B_paths = sorted(make_dataset(self.dir_B))

        ### instance maps
        if not opt.no_instance:
            self.dir_inst = os.path.join(opt.dataroot, opt.phase + '_inst')
            self.inst_paths = sorted(make_dataset(self.dir_inst))

        ### load precomputed instance-wise encoded features
        if opt.load_features:                              
            self.dir_feat = os.path.join(opt.dataroot, opt.phase + '_feat')
            print('----------- loading features from %s ----------' % self.dir_feat)
            self.feat_paths = sorted(make_dataset(self.dir_feat))

        self.dataset_size = len(self.A_paths) 
      
    def __getitem__(self, index):        
        ### input A (label maps)
        A_path = self.A_paths[index]              
        A = Image.open(A_path).convert('RGB')  
        params = get_params(self.opt, A.size)

        B_tensor = inst_tensor = feat_tensor = 0
        ### input B (real images)
        if self.opt.isTrain or self.opt.use_encoded_image:
            B_path = self.B_paths[index]   
            B = Image.open(B_path).convert('RGB')

            A = np.array(A)
            B = np.array(B)

            # transformed = transform_image(image=A)
            # A = transformed['image']

            transformed = transform(image=A, style=B)

            A_tensor = transformed['image']
            B_tensor = transformed['style']
        else:
            transform_A = get_transform(self.opt, params)
            A_tensor = transform_A(A)             

        input_dict = {'label': A_tensor, 'inst': inst_tensor, 'image': B_tensor, 
                        'feat': feat_tensor, 'path': A_path}

        return input_dict

    def __len__(self):
        return len(self.A_paths) // self.opt.batchSize * self.opt.batchSize

    def name(self):
        return 'AlignedDataset'
```

like this?

**Comment by watertianyi** [comment]
@jjeamin Thank you for your prompt answer! Do you mean to add the above operations to retraining?

**Comment by jjxxmiin** [comment]
Yes it is :)

**Comment by watertianyi** [comment]
@jjeamin 
I have trained 3000 pairs of data, and want to add another 2000 pairs to continue training, using the following command:
python train.py --name comics --dataroot ./datasets/comics3Kto5K --loadSize 512 --label_nc 0 --no_instance --which_epoch 200 --niter 200 --niter_decay 200 --continue_train
But the error is as follows:
RuntimeError: CUDA out of memory. Tried to allocate 98.00 MiB (GPU 0; 11.76 GiB total capacity; 8.86 GiB already allocated; 113.56 MiB free; 8.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragment
What is going on?

**Comment by jjxxmiin** [comment]
This message means gpu memory leak problem. 

You need to reduce the batch size or add GPUs.

**Comment by watertianyi** [comment]
------------ Options -------------
batchSize: 1
beta1: 0.5
checkpoints_dir: ./checkpoints0310
continue_train: False
data_type: 32
dataroot: ./datasets/comics3Kto5K
debug: False
display_freq: 100
display_winsize: 512
feat_num: 3
fineSize: 512
fp16: False
gpu_ids: [0]
input_nc: 3
instance_feat: False
isTrain: True
label_feat: False
label_nc: 0
lambda_feat: 10.0
loadSize: 512
load_features: False
load_pretrain: ./checkpoints0310/comics/
local_rank: 0
lr: 0.0002
max_dataset_size: inf
model: pix2pixHD
nThreads: 2
n_blocks_global: 9
n_blocks_local: 3
n_clusters: 10
n_downsample_E: 4
n_downsample_global: 4
n_layers_D: 3
n_local_enhancers: 1
name: comics
ndf: 64
nef: 16
netG: local
ngf: 32
niter: 100
niter_decay: 100
niter_fix_global: 0
no_flip: False
no_ganFeat_loss: False
no_html: False
no_instance: True
no_lsgan: False
no_vgg_loss: False
norm: instance
num_D: 2
output_nc: 3
phase: train
pool_size: 0
print_freq: 100
resize_or_crop: scale_width
save_epoch_freq: 10
save_latest_freq: 1000
serial_batches: False
tf_log: False
use_dropout: False
verbose: False
which_epoch: latest
-------------- End ----------------
The above are my parameters，

Why did this cuda memory problem not occur when training 3000 pairs of data before, and now this happens when 2000 pairs of data are added to train on the model of 3000 pairs of data?

**Comment by watertianyi** [comment]
> This message means gpu memory leak problem.
> 
> You need to reduce the batch size or add GPUs.

I found a problem. Using the above code requires a larger memory GPU than before. What is the size of the GPU you are using?

**Comment by jjxxmiin** [comment]
I use two RTX3090Ti. 
I'm sorry for the late reply.

**Comment by watertianyi** [comment]
@jjeamin 
It is found that the quality of the training data is the key point. I changed a batch of data for training, and the effect is better than the current data. Even if the current data is enhanced with data, the effect is not good.

**Comment by jjxxmiin** [comment]
Good, quality and quantity are very important for image deep learning. Thanks. 
If you can that I recommend using low-quality image filtering technology.
